// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InsterNav(arg1) {
  return window['go']['main']['App']['InsterNav'](arg1);
}

export function ListNav() {
  return window['go']['main']['App']['ListNav']();
}

export function LoadData(arg1) {
  return window['go']['main']['App']['LoadData'](arg1);
}

export function OpenDataFile(arg1) {
  return window['go']['main']['App']['OpenDataFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
