// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function InsterNav(arg1:entity.Nav):Promise<boolean|Error>;

export function ListNav():Promise<Array<entity.Nav>|Error>;

export function LoadData(arg1:string):Promise<any|Error>;

export function OpenDataFile(arg1:string):Promise<boolean|Error>;

export function Greet(arg1:string):Promise<string>;
